import { ButtonProps } from '../components'

export const testingGrid: Pick<
  ButtonProps,
  'color' | 'size' | 'icon' | 'dropdown'
>[] = [
  { color: 'primary', size: 'large' },
  { color: 'primary', size: 'medium' },
  { color: 'primary', size: 'small' },
  { color: 'secondary', size: 'large' },
  { color: 'secondary', size: 'medium' },
  { color: 'secondary', size: 'small' },
  { color: 'success', size: 'large' },
  { color: 'success', size: 'medium' },
  { color: 'success', size: 'small' },
  { color: 'error', size: 'large' },
  { color: 'error', size: 'medium' },
  { color: 'error', size: 'small' },
  { color: 'primary', size: 'large', icon: true },
  { color: 'primary', size: 'large', icon: true },
  { color: 'primary', size: 'small', icon: true },
  { color: 'secondary', size: 'large', icon: true },
  { color: 'secondary', size: 'medium', icon: true },
  { color: 'secondary', size: 'small', icon: true },
  { color: 'success', size: 'large', icon: true },
  { color: 'success', size: 'medium', icon: true },
  { color: 'success', size: 'small', icon: true },
  { color: 'error', size: 'large', icon: true },
  { color: 'error', size: 'medium', icon: true },
  { color: 'error', size: 'small', icon: true },
  { color: 'primary', size: 'large', dropdown: true },
  { color: 'primary', size: 'large', dropdown: true },
  { color: 'primary', size: 'small', dropdown: true },
  { color: 'secondary', size: 'large', dropdown: true },
  { color: 'secondary', size: 'medium', dropdown: true },
  { color: 'secondary', size: 'small', dropdown: true },
  { color: 'success', size: 'large', dropdown: true },
  { color: 'success', size: 'medium', dropdown: true },
  { color: 'success', size: 'small', dropdown: true },
  { color: 'error', size: 'large', dropdown: true },
  { color: 'error', size: 'medium', dropdown: true },
  { color: 'error', size: 'small', dropdown: true },
  { color: 'primary', size: 'large', dropdown: true, icon: true },
  { color: 'primary', size: 'large', dropdown: true, icon: true },
  { color: 'primary', size: 'small', dropdown: true, icon: true },
  { color: 'secondary', size: 'large', dropdown: true, icon: true },
  { color: 'secondary', size: 'medium', dropdown: true, icon: true },
  { color: 'secondary', size: 'small', dropdown: true, icon: true },
  { color: 'success', size: 'large', dropdown: true, icon: true },
  { color: 'success', size: 'medium', dropdown: true, icon: true },
  { color: 'success', size: 'small', dropdown: true, icon: true },
  { color: 'error', size: 'large', dropdown: true, icon: true },
  { color: 'error', size: 'medium', dropdown: true, icon: true },
  { color: 'error', size: 'small', dropdown: true, icon: true }
]
